development:
  bucket: overniteme-dev
  access_key_id: ENV['S3_ACCESS_KEY']
  secret_access_key: ENV['S3_SECRET']
test:
  bucket: overniteme-test
  access_key_id: xxx
  secret_access_key: xxx
production:
  bucket: overniteme-prod
  access_key_id: ENV['S3_ACCESS_KEY']
  secret_access_key: ENV['S3_SECRET']